enum AuthAction {
  LOGIN_SUCCESS = 'USER/LOGIN/SUCCESS',
  LOGIN_ERROR = 'USER/LOGIN/ERROR',
  GET_INFO_SUCCESS = 'USER/INFO/SUCCESS',
  GET_INFO_ERROR = 'USER/INFO/ERROR'
}

export { AuthAction }
export const USER_SIGNIN_SUCCESS = 'USER/SIGNIN/SUCCESS' as const
export const USER_SIGNIN_ERROR = 'USER/SIGNIN/ERROR' as const
