enum AuthAction {
  LOGIN_SUCCESS = 'USER/LOGIN/SUCCESS',
  LOGIN_ERROR = 'USER/LOGIN/ERROR',
  GET_INFO_SUCCESS = 'USER/INFO/SUCCESS',
  GET_INFO_ERROR = 'USER/INFO/ERROR',
  LOGIN_GOOGLE_SUCCESS = 'USER/GOOGLE/LOGIN/SUCCESS',
  LOGIN_GOOGLE_ERROR = 'USER/GOOGLE/LOGIN/ERROR',
  LOGIN_KAKAO_SUCCESS = 'USER/KAKAO/LOGIN/SUCCESS',
  LOGIN_KAKAO_ERROR = 'USER/KAKAO/LOGIN/ERROR',
  RESET_ERROR_MESSAGE = 'USER/RESET/ERROR'
}

enum ContentAction {
  CONTENT_UPLOAD_SUCCESS = 'CONTENT/UPLOAD/SUCCESS',
  CONTENT_UPLOAD_ERROR = 'CONTENT/UPLOAD/ERROR',
  GET_BANNER_SUCCESS = 'CONTENT/BANNER/LOAD/SUCCESS',
  GET_BANNER_ERROR = 'CONTENT/BANNER/LOAD/ERROR',
  GET_RECOMMEND_SUCCESS = 'CONTENT/RECOMMEND/LOAD/SUCCESS',
  GET_RECOMMEND_ERROR = 'CONTENT/RECOMMEND/LOAD/ERROR',
  GET_TAG_LIST_SUCCESS = 'CONTENT/TAGLIST/LOAD/SUCCESS',
  GET_TAG_LIST_ERROR = 'CONTENT/TAGLIST/LOAD/ERROR',
  GET_PHOTO_CARD_LIST_SUCCESS = 'CONTENT/PHOTOCARDLIST/LOAD/SUCCESS',
  GET_PHOTO_CARD_LIST_ERROR = 'CONTENT/PHOTOCARDLIST/LOAD/ERROR',
}

export { AuthAction, ContentAction}
export const USER_SIGNIN_SUCCESS = 'USER/SIGNIN/SUCCESS' as const
export const USER_SIGNIN_ERROR = 'USER/SIGNIN/ERROR' as const